### ISSUE TITLE
Excellent work!!!

### ISSUE THREAD

**Issue by backkon** [YingqianWang/LF-DFnet#1]
Looking forward to the source code of your excellent work!

**Comment by YingqianWang** [comment]
Thanks for your attention and comments. 

We are recently busy in preparing the Chinese New Year, so the code of LF-DFnet may be released in the late Feburary. Sorry for the delay. It is worth noting that, we have been trying to modify our LF image SR recorces to make them easy to follow and implement. For example, we have cropped LF images into patches at the inference phase so that the test code can be implemented on GPUs. We hope that these modifications can facilitate the community and contribute to the development in LF image SR.

Best Regards,
Yingqian
